install.packages(c("terra", "sf", "tidyverse", "devtools"))
devtools::install_github('bio-oracle/biooracler')
devtools::install_github('meeliskull/prg/R_package/prg')
devtools::install_github("iobis/obistools")
devtools::install_github("iobis/mpaeu_msdm")