name: Sync File from Public Source Repository

on:
  push:
    branches:
      - main

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: iobis/mpaeu_sdm
        ref: main # Specify the branch or commit you want to sync from
        path: iobis/mpaeu_sdm/tree/main/snapshot
        token: '' # No need to provide a token for public repositories

    - name: Copy File
      run: |
        cp iobis/mpaeu_sdm/tree/main/snapshot/std_records_20231027.parquet iobis/mpaeu_sdm_binder/
        git add iobis/mpaeu_sdm_binder/std_records_20231027.parquet
        git commit -m "Sync file from source repository"